FROM openjdk:11-jre-slim

# Set the working directory for your app
WORKDIR /usr/src/app

# Copy the JAR file into the container at the working directory
COPY target/NtiTestApp-1.0.0.jar NtiTestApp-1.0.0.jar

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the JAR file using the java command
CMD ["java", "-jar", "NtiTestApp-1.0.0.jar"]