FROM maven:3.8.3-openjdk-11-slim AS build
WORKDIR /root
COPY . .
RUN ./gradlew build

FROM openjdk:11-jre-slim
WORKDIR /root
COPY --from=build /app/target/NtiTestApp-all.jar /NtiTestApp-all.jar
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./app.jar"]